# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ja-JP
early_access: true
reviews:
  profile: assertive
  high_level_summary: false
  collapse_walkthrough: false
  sequence_diagrams: false
  suggested_reviewers: false
  poem: false
  auto_review:
    drafts: true
    base_branches:
      - main
code_generation:
  docstrings:
    language: ja-JP
issue_enrichment:
  auto_enrich:
    enabled: true
issue_enrichment:
  auto_enrich:
    enabled: true
